project:
  type: website
  preview:
    port: 7777
  render:
    - "*.qmd"

website:
  title: "Ahad Jawaid"
  search: false
  back-to-top-navigation: true
  site-url: https://ahadjawaid.github.io/personal-website
  description: "Ahad Jawaid's Website!"
  favicon: favicon.ico


  navbar:
    logo: "assets/chip.png"
    logo-alt: "computer chip icon"

    tools:
      - icon: twitter
        href: https://twitter.com\_ahadj_
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/ahadjawaid/personal-website
          - text: Report Bug
            href: https://github.com/ahadjawaid/personal-website/issues

    right:
      - text: Home
        href: index.qmd
        icon: house-door

      - text: Blog
        href: blog/index.qmd
        icon: newspaper

      - text: About
        href: about.qmd
        icon: person

  page-footer:
    border: false
    left: "Copyright 2023, Ahad Jawaid"
    right:
      - icon: twitter
        href: https://twitter.com\_ahadj_
      - icon: github
        href: https://github.com/ahadjawaid/personal-website

  comments:
    giscus:
      repo: ahadjawaid/personal-website
      repo-id: R_kgDOJrWaMQ
      category: Giscus Comments
      category-id: DIC_kwDOJrWaMc4CXAID
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: light

  twitter-card:
    title: "Ahad Jawaid"
    description: "Ahad Jawaid's Website"
    image: clouds.png
    card-style: summary_large_image
    creator: "@_ahadj_"
    site: "@_ahadj_"
  open-graph:
    description: "Ahad Jawaid's Website"
    image: clouds.png


format:
  html:
    theme: zephyr
    css: styles.css
    smooth-scroll: true
    toc: true
    